### ISSUE TITLE
'get_by_name' does not work for Nodes

### ISSUE THREAD

**Issue by binarybana** [kelproject/pykube#47]
```
x = pykube.Node.objects(api)
x.get_by_name('ip-10-6-41-253.us-west-2.compute.internal')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-37-199fc29ba186> in <module>()
----> 1 x.get_by_name('ip-10-6-41-253.us-west-2.compute.internal')

/usr/lib/python2.7/site-packages/pykube/query.pyc in get_by_name(self, name)
     55         if self.api_obj_class.version:
     56             kwargs["version"] = self.api_obj_class.version
---> 57         r = self.api.get(**kwargs)
     58         if not r.ok:
     59             if r.status_code == 404:

/usr/lib/python2.7/site-packages/pykube/http.pyc in get(self, *args, **kwargs)
    101            - `kwargs`: Keyword arguments
    102         """
--> 103         return self.session.get(*args, **self.get_kwargs(**kwargs))
    104 
    105     def options(self, *args, **kwargs):

/usr/lib/python2.7/site-packages/pykube/http.pyc in get_kwargs(self, **kwargs)
     68             url = url[1:]
     69         bits.append(url)
---> 70         kwargs["url"] = self.url + posixpath.join(*bits)
     71         return kwargs
     72 

/usr/lib64/python2.7/posixpath.pyc in join(a, *p)
     66     path = a
     67     for b in p:
---> 68         if b.startswith('/'):
     69             path = b
     70         elif path == '' or path.endswith('/'):

AttributeError: 'NoneType' object has no attribute 'startswith'
```
The problem is that `namespace` gets set to 'None' by the `BaseQuery` constructor, and then this 'None' value tries to get `os.path.join`ed to the API:
```
ipdb> bits
['/api', 'v1', 'namespaces', None, 'nodes/ip-10-6-41-253.us-west-2.compute.internal']
```

**Comment by brosner** [comment]
Can you check to see if PR #45 fixes this problem? I would prefer that solution over this one.

**Comment by brosner** [comment]
Can this be retested on the latest release, v0.12.0 to if resolution is present. Thank you.

**Comment by brosner** [comment]
I can confirm this works on 0.12.0:

```
>>> import pykube
>>> kc = pykube.KubeConfig.from_file("~/.kube/config")
>>> api = pykube.HTTPClient(kc)
>>> pykube.Node.objects(api).get_by_name("127.0.0.1")
<Node 127.0.0.1>
```
